### PR TITLE
1

### PR DESCRIPTION
**Pull request by Vinatorul**
This change is [Reviewable](https://reviewable.io/reviews/gitlings/gitlings/1)

### CODE REVIEW

**Comment by mvlabat** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/gitlings/gitlings/1)*

**Comment by Vinatorul** [comment]
@homu r-

**Comment by Vinatorul** [comment]
@homu r+

**Comment by Vinatorul** [comment]
@homu r-

**Pull request closed without merging**
